### PR TITLE
Fix missbehavior in reset

### LINKED ISSUE #57: Bug - No se resetea el mundo
En ocasiones, cuando guardo el OUT de un mundo, y luego trato de resetear el mundo a su estado inicial, no lo hace. No he podido identificar cuando pasa, he tratado de reproducir el bug pero no he podido, pero me sigue pasando.

### PR DESCRIPTION
**Pull request by pacharrin**
this should fix #57 

also some love to dragging and corrected a bug with right click on firefox

### CODE REVIEW

File: js/main.js [hunk 1]
```diff
@@ -949,7 +949,7 @@ $(document).ready(function(){
       }
     }
   });
-  $("#world").bind("contextmenu", function(e){
+  $("#world").bind("contextmenu", function(event){
```
Comment (lhchavez) [inline js/main.js]: herp derp. gracias!
